FROM golang:1.21-bullseye AS builder

# Set the working directory inside the container
WORKDIR /app

# Copy the source code into the container
COPY go.mod go.sum ./
RUN go mod download

COPY . ./

EXPOSE 8080 8081
VOLUME ["/config", "/nzbs"]