// Code generated by MockGen. DO NOT EDIT.
// Source: ./nntp.go

// Package nntpcli is a generated GoMock package.
package nntpcli

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// Dial mocks base method.
func (m *MockClient) Dial(address string, port int, useTLS, insecureSSL, downloadOnly bool) (Connection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Dial", address, port, useTLS, insecureSSL, downloadOnly)
	ret0, _ := ret[0].(Connection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Dial indicates an expected call of Dial.
func (mr *MockClientMockRecorder) Dial(address, port, useTLS, insecureSSL, downloadOnly interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Dial", reflect.TypeOf((*MockClient)(nil).Dial), address, port, useTLS, insecureSSL, downloadOnly)
}
